/*
 *  Copyright (C) 2010 - 2015 Leonid Kostrykin
 *
 *  Chair of Medical Engineering (mediTEC)
 *  RWTH Aachen University
 *  Pauwelsstr. 20
 *  52074 Aachen
 *  Germany
 *
 */

#ifndef VERSION_H_3294808493
#define VERSION_H_3294808493

/** \file   Version.h
  * \brief  Defines the macros
  *             \ref CARNADICOM_MAJOR_VERSION,
  *             \ref CARNADICOM_MINOR_VERSION,
  *             \ref CARNADICOM_PATCH_VERSION.
  *
  * \attention
  * This file is automatically generated from `misc/Version.h.in`,
  * thus **DO NOT CHANGE THIS FILE DIRECTLY!!!**
  *
  * \author Leonid Kostrykin
  * \date   8.4.15
  */



// ----------------------------------------------------------------------------------
// CARNADICOM_MAJOR_VERSION
// ----------------------------------------------------------------------------------

/** \brief
  * Defines the \ref VersioningPolicies "API major version number".
  */
#define CARNADICOM_MAJOR_VERSION 1



// ----------------------------------------------------------------------------------
// CARNADICOM_MINOR_VERSION
// ----------------------------------------------------------------------------------

/** \brief
  * Defines the \ref VersioningPolicies "API minor version number".
  */
#define CARNADICOM_MINOR_VERSION 0



// ----------------------------------------------------------------------------------
// CARNADICOM_PATCH_VERSION
// ----------------------------------------------------------------------------------

/** \brief
  * Defines the \ref VersioningPolicies "API patch version number".
  */
#define CARNADICOM_PATCH_VERSION 0



#endif // VERSION_H_3294808493

